CREATE TABLE THEATRE (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE MOVIES_RUNNING (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE MOVIES_RUNNING_IN_THEATRE(
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    theatre_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL
);

INSERT INTO THEATRE (id, name) VALUES (1, 'PVR');
INSERT INTO THEATRE (id, name) VALUES (2, 'INOX');
INSERT INTO THEATRE (id, name) VALUES (3, 'SATYAM');
INSERT INTO THEATRE (id, name) VALUES (4, 'DEVI');
INSERT INTO THEATRE (id, name) VALUES (5, 'IMAX');

INSERT INTO MOVIES_RUNNING (name) VALUES ('RRR');
INSERT INTO MOVIES_RUNNING (name) VALUES ('VIKRAM');
INSERT INTO MOVIES_RUNNING (name) VALUES ('AVENGERS');

INSERT INTO MOVIES_RUNNING_IN_THEATRE (theatre_id, movie_id) VALUES (1, 1);
INSERT INTO MOVIES_RUNNING_IN_THEATRE ( theatre_id, movie_id) VALUES (1, 2);
INSERT INTO MOVIES_RUNNING_IN_THEATRE ( theatre_id, movie_id) VALUES (5, 3);
INSERT INTO MOVIES_RUNNING_IN_THEATRE ( theatre_id, movie_id) VALUES (3, 1);
INSERT INTO MOVIES_RUNNING_IN_THEATRE ( theatre_id, movie_id) VALUES (4, 1);
INSERT INTO MOVIES_RUNNING_IN_THEATRE ( theatre_id, movie_id) VALUES (2, 2);
