CREATE TABLE THEATRE (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO THEATRE (id, name) VALUES (1, 'PVR');
INSERT INTO THEATRE (id, name) VALUES (2, 'INOX');
INSERT INTO THEATRE (id, name) VALUES (3, 'SATYAM');
INSERT INTO THEATRE (id, name) VALUES (4, 'DEVI');
INSERT INTO THEATRE (id, name) VALUES (5, 'IMAX');